# Configuration for Corne split wireless with Nice!Nano v2 and Nice!View
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view